version: '3.9'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecoscooting-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    # volumes:
    #   - /my/own/datadir:/var/lib/mysql

# docker-compose exec db mysql -u root -p -D ecoscooting-db -e "SELECT * FROM books"